# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created: Fri Dec 26 11:33:09 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Player(object):
    def setupUi(self, Player):
        Player.setObjectName("Player")
        Player.resize(320, 240)
        self.centralWidget = QtGui.QWidget(Player)
        self.centralWidget.setObjectName("centralWidget")
        self.stackedWidget = QtGui.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 320, 200))
        self.stackedWidget.setObjectName("stackedWidget")
        self.userPage = QtGui.QWidget()
        self.userPage.setObjectName("userPage")
        self.userList = QtGui.QListWidget(self.userPage)
        self.userList.setGeometry(QtCore.QRect(0, 0, 320, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userList.sizePolicy().hasHeightForWidth())
        self.userList.setSizePolicy(sizePolicy)
        self.userList.setMinimumSize(QtCore.QSize(320, 200))
        self.userList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.userList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.userList.setAutoScroll(False)
        self.userList.setIconSize(QtCore.QSize(50, 50))
        self.userList.setProperty("isWrapping", False)
        self.userList.setGridSize(QtCore.QSize(3, 1))
        self.userList.setViewMode(QtGui.QListView.ListMode)
        self.userList.setUniformItemSizes(False)
        self.userList.setObjectName("userList")
        QtGui.QListWidgetItem(self.userList)
        QtGui.QListWidgetItem(self.userList)
        QtGui.QListWidgetItem(self.userList)
        self.stackedWidget.addWidget(self.userPage)
        self.playerPage = QtGui.QWidget()
        self.playerPage.setObjectName("playerPage")
        self.albumTextLabel = QtGui.QLabel(self.playerPage)
        self.albumTextLabel.setGeometry(QtCore.QRect(70, 180, 180, 20))
        self.albumTextLabel.setObjectName("albumTextLabel")
        self.browseLeft = QtGui.QPushButton(self.playerPage)
        self.browseLeft.setEnabled(True)
        self.browseLeft.setGeometry(QtCore.QRect(0, 0, 70, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseLeft.sizePolicy().hasHeightForWidth())
        self.browseLeft.setSizePolicy(sizePolicy)
        self.browseLeft.setMinimumSize(QtCore.QSize(0, 0))
        self.browseLeft.setMaximumSize(QtCore.QSize(500, 500))
        self.browseLeft.setObjectName("browseLeft")
        self.albumImageLabel = QtGui.QLabel(self.playerPage)
        self.albumImageLabel.setGeometry(QtCore.QRect(70, 0, 180, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.albumImageLabel.sizePolicy().hasHeightForWidth())
        self.albumImageLabel.setSizePolicy(sizePolicy)
        self.albumImageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.albumImageLabel.setMaximumSize(QtCore.QSize(200, 200))
        self.albumImageLabel.setBaseSize(QtCore.QSize(200, 200))
        self.albumImageLabel.setObjectName("albumImageLabel")
        self.browseRight = QtGui.QPushButton(self.playerPage)
        self.browseRight.setGeometry(QtCore.QRect(250, 0, 70, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseRight.sizePolicy().hasHeightForWidth())
        self.browseRight.setSizePolicy(sizePolicy)
        self.browseRight.setMinimumSize(QtCore.QSize(0, 0))
        self.browseRight.setMaximumSize(QtCore.QSize(200, 200))
        self.browseRight.setObjectName("browseRight")
        self.stackedWidget.addWidget(self.playerPage)
        self.controlWidget = QtGui.QWidget(self.centralWidget)
        self.controlWidget.setGeometry(QtCore.QRect(0, 200, 320, 40))
        self.controlWidget.setObjectName("controlWidget")
        self.nextButton = QtGui.QPushButton(self.controlWidget)
        self.nextButton.setGeometry(QtCore.QRect(210, 3, 45, 35))
        self.nextButton.setMinimumSize(QtCore.QSize(45, 35))
        self.nextButton.setMaximumSize(QtCore.QSize(45, 35))
        self.nextButton.setObjectName("nextButton")
        self.stopButton = QtGui.QPushButton(self.controlWidget)
        self.stopButton.setGeometry(QtCore.QRect(110, 3, 45, 35))
        self.stopButton.setMinimumSize(QtCore.QSize(45, 35))
        self.stopButton.setMaximumSize(QtCore.QSize(45, 35))
        self.stopButton.setObjectName("stopButton")
        self.menuButton = QtGui.QPushButton(self.controlWidget)
        self.menuButton.setGeometry(QtCore.QRect(270, 3, 45, 35))
        self.menuButton.setMaximumSize(QtCore.QSize(45, 35))
        self.menuButton.setObjectName("menuButton")
        self.userButton = QtGui.QPushButton(self.controlWidget)
        self.userButton.setGeometry(QtCore.QRect(5, 3, 45, 35))
        self.userButton.setMinimumSize(QtCore.QSize(45, 35))
        self.userButton.setMaximumSize(QtCore.QSize(45, 35))
        self.userButton.setObjectName("userButton")
        self.playPauseButton = QtGui.QPushButton(self.controlWidget)
        self.playPauseButton.setGeometry(QtCore.QRect(160, 3, 45, 35))
        self.playPauseButton.setMinimumSize(QtCore.QSize(45, 35))
        self.playPauseButton.setMaximumSize(QtCore.QSize(45, 35))
        self.playPauseButton.setObjectName("playPauseButton")
        self.prevButton = QtGui.QPushButton(self.controlWidget)
        self.prevButton.setGeometry(QtCore.QRect(60, 3, 45, 35))
        self.prevButton.setMinimumSize(QtCore.QSize(45, 35))
        self.prevButton.setMaximumSize(QtCore.QSize(45, 35))
        self.prevButton.setObjectName("prevButton")
        Player.setCentralWidget(self.centralWidget)

        self.retranslateUi(Player)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Player)

    def retranslateUi(self, Player):
        Player.setWindowTitle(QtGui.QApplication.translate("Player", "Player", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.userList.isSortingEnabled()
        self.userList.setSortingEnabled(False)
        self.userList.item(0).setText(QtGui.QApplication.translate("Player", "Andy", None, QtGui.QApplication.UnicodeUTF8))
        self.userList.item(1).setText(QtGui.QApplication.translate("Player", "Rosemary", None, QtGui.QApplication.UnicodeUTF8))
        self.userList.item(2).setText(QtGui.QApplication.translate("Player", "Eliot", None, QtGui.QApplication.UnicodeUTF8))
        self.userList.setSortingEnabled(__sortingEnabled)
        self.albumTextLabel.setText(QtGui.QApplication.translate("Player", "Current Song Info", None, QtGui.QApplication.UnicodeUTF8))
        self.browseLeft.setText(QtGui.QApplication.translate("Player", "Prev\n"
"Album", None, QtGui.QApplication.UnicodeUTF8))
        self.albumImageLabel.setText(QtGui.QApplication.translate("Player", "Current Album Info", None, QtGui.QApplication.UnicodeUTF8))
        self.browseRight.setText(QtGui.QApplication.translate("Player", "Next\n"
"Album", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("Player", "Next\n"
"Song", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("Player", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.menuButton.setText(QtGui.QApplication.translate("Player", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.userButton.setText(QtGui.QApplication.translate("Player", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.playPauseButton.setText(QtGui.QApplication.translate("Player", "Play/\n"
"Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.prevButton.setText(QtGui.QApplication.translate("Player", "Prev\n"
"Song", None, QtGui.QApplication.UnicodeUTF8))

